# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'GoBus' do
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native'
    
    pod 'GoogleMaps', '~>2.5.0'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

end
